version: 2.1

aktion:
  echo "Gebe Umgebung aus" 
  ls -lart

jobs:
  syntactic-close:
    docker:
      # - image: ubuntu-2004:202010-01
      - image: silex/emacs:27.2
    working_directory: ~/syntactic-close
    steps:
      - run: apt update && apt install -y git ssh emacs
      - checkout
      - run:
          name: Umgebung
          command:
            echo "Gebe Umgebung aus"; ls -lart

      - run:
          name: ERT tests
          command: |
          emacs -Q --batch \
            --eval "(message (emacs-version))" \
            --eval "(message (getenv \"PWD\"))" \
            --eval "(load \"/root/syntactic-close/syntactic-close.el\")" \
            --eval "(sit-for 1)" \
            -f ert-run-tests-batch-and-exit

workflows:
  syntactic-close-workflow:
    jobs:
      - syntactic-close  
